# Generated by Django 4.2.7 on 2023-12-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
    ]
