# Generated by Django 4.2.7 on 2023-12-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_verified_user_ver_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='442095515327', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
