# Generated by Django 4.2.7 on 2023-11-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_pudlished_blog_slug_blog_views_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
